spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: omar
      password: 123456789
      roles: USER, ADMIN